# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 001f92474ea98a002aaf27b53d480a8703c23f4c4faf14e39e3328260acad9dcb05c76c3a38e01a3b8246a233ef6f093314505ee31b88c1878d75e143e2ebb37

test:
  secret_key_base: 4c003639a4081a4c160073c3492a2b80c5457643cd70684a3859416a96754368c00e8e0dd368ad48fbd7270fb28acce58c0c5258f0236a525a720b03b376e96d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
